### ISSUE TITLE
crime scene example story throws "Operation for value not supported!"

### ISSUE THREAD

**Issue by Myonmu** [JBenda/inkcpp#81]
I was just testing with the crime scene story that comes with inky. (with the command line executable)
Unfortunately the first advance line call directly throws **Operation for value not supported!**
The evaluation stack is at the `Compare the prints on the knife and the window` line of the story when the exception is thrown.

Looks like a not supported ink syntax?

**Comment by JBenda** [comment]
Thanks for bringing this to my notice. It is indeed a feature inkcpp currently is not supporting. Casting types List to `bool` implicit.
This is an oversight, I will see that I will fix it soon.

My current guess is that an empty list will evaluate to false, I'm currently unable to find documentation for that case .

**Comment by Myonmu** [comment]
> Thanks for bringing this to my notice. It is indeed a feature inkcpp currently is not supporting. Casting types List to `bool` implicit.
> This is an oversight, I will see that I will fix it soon.
> 
> My current guess is that an empty list will evaluate to false, I'm currently unable to find documentation for that case .

I found this: https://github.com/inkle/ink/blob/master/Documentation/WritingWithInk.md#testing-for-emptiness

**Comment by JBenda** [comment]
Added the missing functionality and a bit more, is currently online at [fix/ListBoolOperations](https://github.com/JBenda/inkcpp/tree/fix/ListBoolOperations). The matching release will be there soon (maybe a week?)
