### ISSUE TITLE
Inklecate failed with exit code 1

### ISSUE THREAD

**Issue by marekdaniluk** [JBenda/inkcpp#88]
Hi,
I am trying to build inkcpp with CMake using instructions from this [link](https://github.com/JBenda/inkcpp/wiki/building#cmake-example). I generated VS2022 solution for Windows and tried to install the library, but an error "Inklecate failed with exit code 1" occurred during inkcpp_test build.

Is this a known issue? How can I fix it?

**Comment by JBenda** [comment]
Hey, this sounds like `inklecate` is not in your path.
The easiest way is to add INKLECATE with value `C:\YOUR_PATH\inkcpp\build\unreal\inkcpp\Source\ThirdParty\inklecate\windows\inklecate.exe` to your path.
Best test it once with `%INKLECATE%`.
Then it should build.

Please keep me updated about your progress.

**Comment by JBenda** [comment]
Also I recognized that the CmakeLists.txt file in the example you linked is outdated.
You need `CXX_STANDARD 20` instead of `CXX_STANDARD 17`.

**Comment by marekdaniluk** [comment]
I set `%INKLECATE%` and it works like a charm, thanks :). Still, would it be possible to add a CMake option to install library without tests or run tests without inklecate?

**Comment by JBenda** [comment]
Nice :)
That's a good idea, an option to disable tests and probably also one to disable the inklecate download.

Running tests without inklecate would miss the goal of checking inklecate compatibility.

INKCPP_TEST: bool : default Off: enables test stuff
INKCPP_INKLECATE: NONE, OS, ALL: default NONE : download inklecate fou your or all OSs

If TEST and INKLECATE= OS|ALL: use download inklecate automatically for test

If INKLECATE=OS|ALL: Put OS inklecate in the install directory of inkcpp_cl

If you try to install the unreal plugin, generate warning/error if no inklecate is installed
